# Generated by Django 3.1.2 on 2020-10-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_auto_20201015_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizz.question'),
        ),
    ]
