# Generated by Django 3.1.2 on 2020-10-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_auto_20201015_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersanswer',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
